// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using schoolAPI.Contexts;

#nullable disable

namespace schoolAPI.Migrations
{
    [DbContext(typeof(DbApplicationContext))]
    [Migration("20221101205835_added_test_data")]
    partial class added_test_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("schoolAPI.Models.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("schoolAPI.Models.StudyProgramme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudyProgrammes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "System Integration"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Development of Large Systems"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Test"
                        });
                });

            modelBuilder.Entity("schoolAPI.Models.StudyProgramme", b =>
                {
                    b.HasOne("schoolAPI.Models.Student", null)
                        .WithMany("AttendingProgrammes")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("schoolAPI.Models.Student", b =>
                {
                    b.Navigation("AttendingProgrammes");
                });
#pragma warning restore 612, 618
        }
    }
}
