version: '3.1'

services:

  db1:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: P@ris2027!
    ports:
      - 5432:5432
volumes:
    pgdata:
    